language: go
go:
  - 1.9

sudo: true

notifications:
  email: false

go_import_path: gopkg.in/sensorbee/pymlstate.v0

before_install:
  - env
  - lsb_release -a
  - sudo apt-get -qq update
  - sudo apt-get -qq install python-dev python-six pkg-config
  - go version

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - go get -t -d -v ./...

before_script:
  - go vet ./...

script:
  - go build -v ./...
  - gotestcover -v -covermode=count -coverprofile=.profile.cov -parallelpackages=1 ./...

after_success:
  - goveralls -coverprofile=.profile.cov -repotoken=$COVERALLS_TOKEN
